blog/urls.py
from django.urls import re_path

from . import views
app_name='blog'
urlpatterns = [
	re_path(r'^create/$', views.create, name='create'),
	re_path(r'^$', views.list, name='list'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

mywebsite/urls.py
from django.urls import re_path, include
from django.contrib import admin

from . import views

urlpatterns = [
	re_path(r'^blog/', include('blog.urls',namespace='blog')),
	re_path(r'^$', views.index, name='index'),
    re_path(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
	judul		= models.CharField(max_length = 100)
	body		= models.TextField()
	author		= models.CharField(max_length = 100)
	
	LIST_CATEGORY = (
		('Jurnal','jurnal'),
		('Berita','berita'),
		('Gosip','gosip'),
		)

	category	= models.CharField(
		max_length = 100,
		choices = LIST_CATEGORY,
		default = 'jurnal',
		)

	def __str__(self):
		return "{}.{}".format(self.id,self.judul)

main/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from .models import PostModel

class PostForm(forms.ModelForm):
	class Meta:
		model = PostModel
		fields = [
			'author',
			'judul',
			'body',
			'category',
		]

		labels = {
			'author':'Penulis',
		}

		widgets = {
			'judul': forms.TextInput(
				attrs = {
					'class':'form-control',
					'placeholder':'isi dengan judul artikel',}
				),

			'author': forms.TextInput(
				attrs = {
					'class':'form-control',
					'placeholder':'nama penulis',}
				),


			'body': forms.Textarea(
				attrs = {
					'class':'form-control',}
				),


			'category': forms.Select(
				attrs = {
					'class':'form-control',
				}
				),
		}

blog/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import PostForm
from .models import PostModel

def list(request):
	posts	= PostModel.objects.all()

	context = {
		'page_title':'Semua Post',
		'posts':posts,
	}

	return render(request,'blog/list.html',context)

def create(request):
	post_form = PostForm(request.POST or None)

	if request.method == 'POST': # POST request dari browser
		if post_form.is_valid():
			post_form.save()

			return redirect('blog:list')

	context = {
		'page_title':'Create Post',
		'post_form':post_form,
	}

	return render(request,'blog/create.html',context)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'page_title':'Home',
	}

	return render(request, 'index.html',context)

blog/templates/blog/create.html
{% extends "base.html" %}

{% block title %}
	{{page_title}}
{% endblock title %}

{% block contents %}
	<h1>{{page_title}}</h1>


	<form method='POST'>
		{% csrf_token %}

		{% for form in post_form %}
			<div class="form-group">
				{{form.label}}
				{{form}}
			</div>
		{% endfor %}
		<button class='btn btn-primary' type="Submit">Kirim</button>
	</form>
{% endblock contents %}

blog/templates/blog/list.html
{% extends "base.html" %}

{% block title %}
	{{page_title}}
{% endblock title %}


{% block contents %}
	
	<h1>{{page_title}}</h1>
	<br>
	{% for post in posts %}

		<h3>{{post.judul}}</h3>
		<h5>penulis: {{post.author}}</h5>
		<h5>category: {{post.category}}</h5>
		<p>{{post.body}}</p>
		
	{% endfor %}
{% endblock contents %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
	{% block title %}
		
	{% endblock title %}
	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-expand-md navbar-light bg-light">
	  <a class="navbar-brand" href="#">Ujian Online</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavDropdown">
	    <ul class="navbar-nav">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'index' %}">Home</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Pendaftaran
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	          <a class="dropdown-item" href="{% url 'blog:list' %}">Data</a>
	          <a class="dropdown-item" href="{% url 'blog:create' %}">Daftar</a>
	        </div>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
	      </li>
	    </ul>
	  </div>
	</nav>
	<div class="container">
		{% block contents %}
			
		{% endblock contents %}
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
	{{page_title}}
{% endblock title %}

{% block contents %}
	<h1>{{page_title}}</h1>
{% endblock contents %}